name: Build (and publish release artifacts)

on:
  push:
    branches:
      - master

#permissions: {}
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs/*
          if-no-files-found: error
  publish:
    needs: build
    if: success() && github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write # needed for creating GH releases
    steps:
      - name: Publish release artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish