name: Build (and publish release artifacts)

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build --no-daemon -i
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: fabric/build/libs/*
          if-no-files-found: error
  publish:
    needs: build
    if: success() && github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write # needed for creating GH releases
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - uses: actions/download-artifact@v4
        with:
          name: libs
          path: fabric/build/libs
      - name: Publish release artifacts
        env:
          ORG_GRADLE_PROJECT_ghToken: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_cfToken: ${{ secrets.CURSEFORGE_TOKEN }}
        run: ./gradlew publish --no-daemon -i